Using new Nemo export_config and --config options
nvidia-riva/nemo2riva pull request #26
Opened 2023-07-12 22:16 UTC by borisfom

2023-07-17 20:53 UTC, messiaen requested changes

2023-07-17 20:53 UTC, messiaen commented on nemo2riva/args.py
> +        "--config",
Should it be called `--export-config` to match nemo?

2023-07-17 20:53 UTC, messiaen commented on nemo2riva/schema.py
> +        conf.export_args.update(kv)
It might be useful to do some error checking / giving useful error messages. Something like

```suggestion
        for key_value in args.config:
            lst = s.split("=")
            if len(lst) != 2:
                raise Exception("Use correct format ...")
            k, v = lst
            conf.export_args[k] = v
```

2023-07-17 21:43 UTC, borisfom commented on nemo2riva/args.py
> +        "--config",
Well, it's --config in Nemo's export.py as well. --export-config may still be cleaner though, for both.

2023-07-17 21:46 UTC, borisfom commented on nemo2riva/schema.py
> +        conf.export_args.update(kv)
Sure, let's do that. I will do another iteration.

2023-07-19 19:27 UTC, messiaen approved these changes

2023-07-19 21:14 UTC, merged